name: cosmic-gala
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pip
  - matplotlib
  - astropy
  - scipy
  - jupyter
  - jupyterlab
  - ipython
  - seaborn
  - pandas
  - pip:
      - gala >= 1.5
      - cosmic-popsynth >= 3.4.6