name: cogsworth
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy == 1.23
  - numba == 0.57
  - pip
  - matplotlib
  - astropy
  - scipy >= 1.7.3
  - jupyter
  - jupyterlab
  - ipython
  - seaborn
  - pandas
  - nose
  - pytables
  - healpy
  - pip:
      - gala >= 1.5
      - cosmic-popsynth >= 3.4.7
      - isochrones @ git+https://github.com/TomWagg/isochrones.git
      - dustmaps
      - gaiaunlimited >= 0.2.0
      - agama