name: cosmic-gala
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy >= 1.23
  - numba >= 0.56
  - pip
  - matplotlib
  - astropy
  - scipy >= 1.7.3
  - jupyter
  - jupyterlab
  - ipython
  - seaborn
  - pandas
  - nose
  - pytables
  - pip:
      - gala >= 1.5
      - cosmic-popsynth >= 3.4.6
      - isochrones >= 2.1
      - dustmaps