name: cosmic-gala
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pip
  - matplotlib
  - gsl
  - astropy
  - scipy
  - jupyter
  - jupyterlab
  - ipython
  - seaborn
  - nbstripout
  - astroquery
  - pytables
  - pip:
      - gala >= 1.5
      - cosmic-popsynth