
# storage for citations a dictionary of tuples, first element bibtex id(s), second element bibtex
CITATIONS = {
    "cogsworth": {
        "tags": ["cogsworth:joss"],
        "bibtex": "TODO"
    },
    "cosmic": {
        "tags": ["cosmic:apj"],
        "bibtex": r"""@ARTICLE{Breivik+2020,
       author = {{Breivik}, Katelyn and {Coughlin}, Scott and {Zevin}, Michael and {Rodriguez}, Carl L. and {Kremer}, Kyle and et al.},
        title = "{COSMIC Variance in Binary Population Synthesis}",
      journal = {\apj},
     keywords = {Compact binary stars, Interacting binary stars, Stellar populations, Gravitational wave astronomy, 283, 801, 1622, 675, Astrophysics - High Energy Astrophysical Phenomena, Astrophysics - Solar and Stellar Astrophysics},
         year = 2020,
        month = jul,
       volume = {898},
       number = {1},
          eid = {71},
        pages = {71},
          doi = {10.3847/1538-4357/ab9d85},
archivePrefix = {arXiv},
       eprint = {1911.00903},
 primaryClass = {astro-ph.HE},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2020ApJ...898...71B},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}}"""
    },
    "gala": {
        "tags": ["gala:joss"],
        "bibtex": r"""@article{gala,
        doi = {10.21105/joss.00388},
        url = {https://doi.org/10.21105%2Fjoss.00388},
        year = 2017,
        month = {oct},
        publisher = {The Open Journal},
        volume = {2},
        number = {18},
        author = {Adrian M. Price-Whelan},
        title = {Gala: A Python package for galactic dynamics},
        journal = {The Journal of Open Source Software}}"""
    },
    "Wagg+2022": {
        "tags": ["Wagg+2022"],
        "bibtex": r"""@ARTICLE{Wagg+2022,
       author = {{Wagg}, T. and {Broekgaarden}, F.~S. and {de Mink}, S.~E. and {Frankel}, N. and {van Son}, L.~A.~C. and et al.},
        title = "{Gravitational Wave Sources in Our Galactic Backyard: Predictions for BHBH, BHNS, and NSNS Binaries Detectable with LISA}",
      journal = {\apj},
     keywords = {Gravitational waves, Gravitational wave detectors, Compact objects, Neutron stars, Stellar mass black holes, Binary stars, Pulsars, Stellar evolution, 678, 676, 288, 1108, 1611, 154, 1306, 1599, Astrophysics - High Energy Astrophysical Phenomena},
         year = 2022,
        month = oct,
       volume = {937},
       number = {2},
          eid = {118},
        pages = {118},
          doi = {10.3847/1538-4357/ac8675},
archivePrefix = {arXiv},
       eprint = {2111.13704},
 primaryClass = {astro-ph.HE},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2022ApJ...937..118W},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}}"""
    },
    "Frankel+2018": {
        "tags": ["Frankel+2018"],
        "bibtex": r"""@ARTICLE{Frankel+2018,
       author = {{Frankel}, Neige and {Rix}, Hans-Walter and {Ting}, Yuan-Sen and {Ness}, Melissa and {Hogg}, David W.},
        title = "{Measuring Radial Orbit Migration in the Galactic Disk}",
      journal = {\apj},
     keywords = {Galaxy: abundances, Galaxy: disk, Galaxy: evolution, Galaxy: formation, ISM: abundances, stars: abundances, Astrophysics - Astrophysics of Galaxies},
         year = 2018,
        month = oct,
       volume = {865},
       number = {2},
          eid = {96},
        pages = {96},
          doi = {10.3847/1538-4357/aadba5},
archivePrefix = {arXiv},
       eprint = {1805.09198},
 primaryClass = {astro-ph.GA},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2018ApJ...865...96F},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}}"""
    },
    "Bovy+2016": {
        "tags": ["Bovy+2016"],
        "bibtex": r"""@ARTICLE{Bovy+2016,
       author = {{Bovy}, Jo and {Rix}, Hans-Walter and {Schlafly}, Edward F. and {Nidever}, David L. and {Holtzman}, Jon A. and et al.},
        title = "{The Stellar Population Structure of the Galactic Disk}",
      journal = {\apj},
     keywords = {Galaxy: abundances, Galaxy: disk, Galaxy: evolution, Galaxy: formation, Galaxy: fundamental parameters, Galaxy: structure, Astrophysics - Astrophysics of Galaxies},
         year = 2016,
        month = may,
       volume = {823},
       number = {1},
          eid = {30},
        pages = {30},
          doi = {10.3847/0004-637X/823/1/30},
archivePrefix = {arXiv},
       eprint = {1509.05796},
 primaryClass = {astro-ph.GA},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2016ApJ...823...30B},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}}"""
    },
    "Bovy+2019": {
        "tags": ["Bovy+2019"],
        "bibtex": r"""@ARTICLE{Bovy+2019,
       author = {{Bovy}, Jo and {Leung}, Henry W. and {Hunt}, Jason A.~S. and {Mackereth}, J. Ted and {Garc{\'\i}a-Hern{\'a}ndez}, Domingo A. and et al.},
        title = "{Life in the fast lane: a direct view of the dynamics, formation, and evolution of the Milky Way's bar}",
      journal = {\mnras},
     keywords = {Galaxy: abundances, Galaxy: bulge, Galaxy: evolution, Galaxy: fundamental parameters, Galaxy: kinematics and dynamics, Galaxy: structure, Astrophysics - Astrophysics of Galaxies, Astrophysics - Cosmology and Nongalactic Astrophysics},
         year = 2019,
        month = dec,
       volume = {490},
       number = {4},
        pages = {4740-4747},
          doi = {10.1093/mnras/stz2891},
archivePrefix = {arXiv},
       eprint = {1905.11404},
 primaryClass = {astro-ph.GA},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2019MNRAS.490.4740B},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}}"""
    },
    "McMillan+2011": {
        "tags": ["McMillan+2011"],
        "bibtex": r"""@ARTICLE{McMillan+2011,
       author = {{McMillan}, Paul J.},
        title = "{Mass models of the Milky Way}",
      journal = {\mnras},
     keywords = {methods: statistical, Galaxy: fundamental parameters, Galaxy: kinematics and dynamics, Astrophysics - Astrophysics of Galaxies},
         year = 2011,
        month = jul,
       volume = {414},
       number = {3},
        pages = {2446-2457},
          doi = {10.1111/j.1365-2966.2011.18564.x},
archivePrefix = {arXiv},
       eprint = {1102.4340},
 primaryClass = {astro-ph.GA},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2011MNRAS.414.2446M},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}}"""
    }
}
