name: Test notebooks

on: 
  pull_request:
    branches: [ main ]
    paths:
      - 'cogsworth/**'
      - 'setup.cfg'
      - 'setup.py'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest coverage pytest-xdist nbmake pytest-cov
        python -m pip install -e .[test]
    - name: Grab the data you need to test observables
      run: |
        # prep the data needed for tests
        python cogsworth/tests/prep_data.py
    - name: Test the tutorial notebooks
      run: |
        # test notebooks in addition to the code
        pytest -n=auto --nbmake "docs/tutorials"
